### ISSUE TITLE
Test we.retail with AEM in nosamplecontent mode

### ISSUE THREAD

**Issue by keepthebyte** [Adobe-Marketing-Cloud/aem-sample-we-retail#89]
We should also test the we.retail code that it runs in an AEM instance in nosamplecontent runmode (https://docs.adobe.com/docs/en/aem/6-1/deploy/configuring/configure-runmodes.html#Using%20samplecontent%20and%20nosamplecontent )

A quick test shows - that the we.retail homepage throws an exception.

GET /content/we-retail/language-masters/en.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "getPath" of null (/apps/we-retail/components/content/product-grid/item/item.js#88)

**Comment by raducotescu** [comment]
The error you mentioned does not relate to the `nosamplecontent` run mode. However I've discovered that in `nosamplecontent` run mode the jQuery version that We.Retail provides cannot be correctly minified by YUI 2.4.8, shipped with AEM 6.2. This is caused by yui/yuicompressor#234.

The solution that I found for now is to downgrade jQuery to 1.12.4, which doesn't use ECMAScript 5+ features.

**Comment by justinedelson** [comment]
@raducotescu the YUI issue was supposed to be fixed by #103. any thoughts why that didn't work and downgrading was necessary?

**Comment by raducotescu** [comment]
The problem was caused by the base client library [1], which embeds jQuery. It seems that embedded client libraries are concatenated in a writer and only then minified. We can either live with the jQuery downgrade (I didn't notice any issues regarding how components render) or try to apply the GCC processor for all We.Retail client libraries. However I think that the downgrade is the simplest way to move forward.

[1] - https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/blob/master/ui.apps/src/main/content/jcr_root/etc/designs/we-retail/clientlib-base/.content.xml
