### ISSUE TITLE
Personalization Content broken

### ISSUE THREAD

**Issue by DominikSuess** [Adobe-Marketing-Cloud/aem-sample-we-retail#90]
The personalization Content & structures are currently
a) not filled properly
b) created with an outdated structure from early 6.2 beta. (including renaming to Area in the level underneath Brand).

**Comment by raducotescu** [comment]
@DominikSuess, could you please provide me with complete steps on how to reproduce this? What are the expected structures and what's different from that?

**Comment by DominikSuess** [comment]
@raducotescu 
Regarding b) this basically is just the name "Master Ambit" which should be renamed to Master area.
For a) I just did discover that when you try to target the master page and placed some of the available offers from offerlibrary on the page which where broken - but I noticed that the content in that area already got changed since then (may), so flaws in that area seem already to have eliminated.

So leaves changing the title to Master Area to match documentation and naming as it would be set when manually creating a new brand.

**Comment by dumasc** [comment]
Hi,
It appear that after a deployment we believe that a new page call “Master Ambit” using the Area template was created under our Brand template. A new layer sort of. From that change, all of campaign path from the Teaser component didn’t get adjusted and now have a wrong location path due to the new layer. Any idea what could have cause this to happen? We are on AEM 6.2.
